project:
  type: book

book:
  title: "Hands On Ensemble Methods With R"
  subtitle: "The Most Accurate Methods Known to Science For Modelling Nature"
  author: "Russ Conte"
  date: "1/9/2026"
  chapters:
    - index.qmd
    - Welcome!.qmd
    - The Hello World! of ensembles.qmd
    - Numeric Data - How To Build 18 Individual Models.qmd
    - Numeric Ensembles - How to Build 14 Ensembles of Models.qmd
    - Classification Data - How to Build Six Classification Models.qmd
    - Classification Ensembles - How to Build Six Classification Ensembles.qmd
    - Logistic Data - How to Build 15 Logistic Models.qmd
    - Logistic Ensembles - How to Build Nine Logistic Ensembles.qmd
    - Forecasting Data - How to Build 27 Forecasting Models.qmd
    - Forecasting Ensembles - How to Build Six Forecasting Ensembles.qmd
    - How to Predict On Totally New Data With Your Trained Models.qmd
    - How Leaders Actually Make Decisions.qmd
    - Building Your Own No Code Solutions.qmd
    - 60 Open Data Sources.qmd
    - Your Journey From Student To Professional To Expert To Leader.qmd
    - Hiring and Getting Hired.qmd
    - Code Of Ethics.qmd
    - Final Comprehensive Project.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

